### ISSUE TITLE
jsonEmptyString not being exported

### ISSUE THREAD

**Issue by emilhaugberg** [purescript-contrib/purescript-argonaut-core#17]
I was wondering why the [jsonEmptyString](https://github.com/purescript-contrib/purescript-argonaut-core/blob/v2.0.1/src/Data/Argonaut/Core.purs#L209) function isn't being exported while the rest of the default functions are?

It's not used anywhere else in the module.

**Comment by garyb** [comment]
I think it's just a mistake. I'd be inclined to just remove it, as unlike empty array/object it doesn't really serve any obvious purpose that I can think of, but since you discovered it was unexported, perhaps I'm wrong?

**Comment by emilhaugberg** [comment]
I'm not sure. I thought it could be useful, but ended up not needing it after all. It could be nice to keep it, just to keep it in line with the rest of the module (`toString`, `isString`, etc.), but like you said it doesn't really server any obvious purpose. As it is right now it's not even exported, so removing it would probably not hurt.
