### ISSUE TITLE
Update on Pursuit?

### ISSUE THREAD

**Issue by jeremyjh** [purescript-contrib/purescript-argonaut-core#28]
This package is blocking some dependencies of mine to upgrade to 0.12. I see the updates are in master, will they be published soon?

**Comment by garyb** [comment]
The release for PS 0.12 is published (v4.0.0), it's just the docs that need publishing on Pursuit. Is this library definitely the problem?

**Comment by sudhirvkumar** [comment]
@garyb how about the other argonaut packages? they are not updated for 0.12.

**Comment by garyb** [comment]
Ah, I'm not too sure about the status of the others, I'm on holiday at the moment. Need to find new maintainers for them too really!

**Comment by jeremyjh** [comment]
Thanks - this library wasn't an issue for me after all, sorry for the noise.

**Comment by garyb** [comment]
No problem! I've updated the docs on pursuit for it now anyway, so thanks for the reminder.
