### ISSUE TITLE
examples from `purescript-agronaut` should be migrated here

### ISSUE THREAD

**Issue by cdepillabout** [purescript-contrib/purescript-argonaut-core#3]
The [example](https://github.com/purescript-contrib/purescript-argonaut/blob/master/examples/Examples/Data/Argonaut/Record.purs) from [purescript-agronaut](https://github.com/purescript-contrib/purescript-argonaut) should be migrated to this repo (or [purescript-agronaut-codecs](https://github.com/purescript-contrib/purescript-argonaut-codecs)?).

This will help future users when they are trying to figure out how to use argonaut.  Don't want users to have to go looking in a deprecated library for examples.

**Comment by jdegoes** [comment]
:+1:

**Comment by thomashoneyman** [comment]
I'm updating the `argonaut-codecs` documentation, which includes updating examples, so I'm going to close this issue. That example is better suited for the `-codecs` repository and will be included there.
